### ISSUE TITLE
Markdown links don't render in footnotes

### ISSUE THREAD

**Issue by GuyAglionby** [iclr-blogposts/2024#72]
Markdown links don't appear to be rendering when they are placed in footnotes. When the example below is rendered, the link in the body appears as expected, but the one in the footnote appears as the markdown.

```yaml
---
layout: distill
title: Example
description: Example
date: 2024-05-07
future: true
authors:
  - name: Anonymous
bibliography: 2024-05-07-distill-example.bib
toc:
  - name: Footnotes
---

## Footnotes

Just wrap the text you would like to show up in a footnote in a `<d-footnote>` tag.
The number of the footnote will be automatically generated.<d-footnote>This will become a hoverable footnote. [Test link](https://www.google.com/)</d-footnote>

***

[Lorem ipsum](https://www.google.com) dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

<img width="986" alt="image" src="https://github.com/iclr-blogposts/2024/assets/1337259/d6a614de-7f78-4f0b-b16d-854a376b0a6a">
